### ISSUE TITLE
生成的exp访问404

### ISSUE THREAD

**Issue by 0ps** [TryGOTry/dogxss#1]
rt。

启动报：`sqlite` is not officially supported, running under compatibility mode.

**Comment by TryGOTry** [comment]
什么系统。db文件放进去了吗

**Comment by TryGOTry** [comment]
sqlite is not officially supported, running under compatibility mode.这个提示是正常的。
要看当前exp目录下有没有生成文件，需要给读写权限，所以用root权限启动最好。
