### ISSUE TITLE
window服务器部署https，存在跨域问题，请问如何解决

### ISSUE THREAD

**Issue by LinLuosheng** [TryGOTry/dogxss#2]
![image](https://github.com/TryGOTry/dogxss/assets/50785665/a1653fee-74f9-403b-b677-e47d27591c34)

**Comment by TryGOTry** [comment]
跨域问题是解决了的,实战linux下部署不存在这个问题,windows下没测试过
https://github.com/TryGOTry/dogxss/blob/main/main.go#L58
